In [1]:
import numpy as np
from collections import Counter

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [2]:
def flatten(container):
    for i in container:
        if isinstance(i, (list, tuple)):
            yield from flatten(i)
        else:
            yield i

In [3]:
def format_input(X):
    if not isinstance(X, (pd.DataFrame, pd.Series)):
        if isinstance(X, dict):
            X = pd.DataFrame(X)
        else:
            X = pd.DataFrame(X,
                             columns=['x' + str(i) for i in range(X.shape[1])])

    return X

In [4]:
X, y = load_iris(return_X_y=True)

In [5]:
print(X.shape)
print(y.shape)

(150, 4)
(150,)


In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=0)

In [7]:
print(X_train.shape)
print(X_test.shape)

(135, 4)
(15, 4)


In [8]:
for i in range(10):
    print(f'{X_train[i]} -> {y_train[i]}')

[4.9 3.6 1.4 0.1] -> 0
[6.  2.9 4.5 1.5] -> 1
[5.5 2.6 4.4 1.2] -> 1
[4.8 3.  1.4 0.3] -> 0
[5.4 3.9 1.3 0.4] -> 0
[5.6 2.8 4.9 2. ] -> 2
[5.6 3.  4.5 1.5] -> 1
[4.8 3.4 1.9 0.2] -> 0
[4.4 2.9 1.4 0.2] -> 0
[6.2 2.8 4.8 1.8] -> 2
